dist: jammy

language: node_js

node_js:
  - '20.15.0'

# USE PNPM
cache:
  npm: false
  directories:
    - '~/.pnpm-store'
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir ~/.pnpm-store

install:
  - pnpm install

script:
  - pnpm lint:script
  - pnpm lint:style
  - pnpm build:prod
