name: s3Sync
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploying application to Amazon S3
        uses: lewandy/vue-s3-deployer@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'
          AWS_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          APP_SOURCE_CODE: dist
          BUILD_COMMAND: 'pnpm build'
